### ISSUE TITLE
Slippage Protection

### ISSUE THREAD

**Issue by boxofscraps** [asgardex/asgard-exchange#102]
When transaction fails due to slippage protection, pending transaction does not show cancelled transaction.  This makes the user wait for the transaction instead of resubmitting the transaction with new settings. 

![fail_tnx](https://user-images.githubusercontent.com/15699137/107348338-bc715e00-6a7b-11eb-8349-427013c4eb7a.JPG)

This issue is related to the block explorer not properly showing failed transaction.  This transaction should not have pending status. 

![failed_tnx_2](https://user-images.githubusercontent.com/15699137/107348313-b67b7d00-6a7b-11eb-9a96-61305a846411.JPG)

https://main.d3mbd42yfy75lz.amplifyapp.com/#/tx/716DB743282881A508B64752D4A30D418E0345BB14F8D54D8B5601322BA14AF9

**Comment by stuartkuentzel** [comment]
closing this as it looks to be an issue with Midgard... https://testnet.midgard.thorchain.info/v2/actions?offset=0&limit=1&txid=716DB743282881A508B64752D4A30D418E0345BB14F8D54D8B5601322BA14AF9. might be good to address this in the THORChain dev thread or on the midgard 2 repo.

**Comment by boxofscraps** [comment]
bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f
