### ISSUE TITLE
Thorchain Block Explorer Link Not Shown

### ISSUE THREAD

**Issue by boxofscraps** [asgardex/asgard-exchange#103]
When swapping using RUNE to another asset, popup does not show thorchain block explorer link.  This is not a problem with swapping using BTC or BNC related assets. 

![half_slippage](https://user-images.githubusercontent.com/15699137/107348680-33a6f200-6a7c-11eb-9488-286ee2d3de45.JPG)

![half_slippage_2](https://user-images.githubusercontent.com/15699137/107348684-34d81f00-6a7c-11eb-9e1d-66a40b9703ff.JPG)

**Comment by stuartkuentzel** [comment]
fixed 👍

**Comment by boxofscraps** [comment]
bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f
