### ISSUE TITLE
Removing Liquidity Shows No Block Explorer

### ISSUE THREAD

**Issue by boxofscraps** [asgardex/asgard-exchange#105]
When removing double sided liquidity, no block explorer is shown to the user.  Recommend linking to both Thorchain explorer and asset B block explorer.

![withdraw_liq_2](https://user-images.githubusercontent.com/15699137/107351545-9948ad80-6a7f-11eb-9482-015dc141830d.JPG)

**Comment by stuartkuentzel** [comment]
@boxofscraps thanks for bringing this up, this has been fixed 👍

**Comment by boxofscraps** [comment]
bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f
