### ISSUE TITLE
Executing Swaps above set slippage tolerance

### ISSUE THREAD

**Issue by bagh0dler** [asgardex/asgard-exchange#107]
Hello,

i am experiencing slippage above the set tolerance.
There is 1) no warning that the slippage exceeds the set tolerance and 2) i am able to execute anyway.

Regards

Set Tolerance:
![image](https://user-images.githubusercontent.com/78794372/107354526-8e693980-6ace-11eb-8906-7d08a571d8b9.png)

Swap 1/2:
![image](https://user-images.githubusercontent.com/78794372/107354650-b5277000-6ace-11eb-8232-6a0d7b47449c.png)

Swap 2/2:
![image](https://user-images.githubusercontent.com/78794372/107354736-cff9e480-6ace-11eb-8eef-2c74a634d0e4.png)

Transaction:
https://testnet-explorer.binance.org/tx/8BD65E3ECEF7214C37827EC9B2A6BDE0DAF45D41040390C06A0C6B660A307DC3

**Comment by stuartkuentzel** [comment]
@bagh0dler nice catch. PR #109 disables the swap button if the slip exceeds the limit.
