### ISSUE TITLE
Failed native RUNE to Testnet BTC swap

### ISSUE THREAD

**Issue by anonthorchad** [asgardex/asgard-exchange#110]
Tried swapping 1000 Native RUNE for Testnet BTC. RUNE was taken but no swap happened. 

Transaction: 38A122AD7C38B2EDBAAD6014337038277FDF18C40B1CFA418BDAAB1D6E2A6311
https://main.d3mbd42yfy75lz.amplifyapp.com/#/tx/38A122AD7C38B2EDBAAD6014337038277FDF18C40B1CFA418BDAAB1D6E2A6311

I tried swapping again with 500 RUNE and the transaction worked. 
Transaction: 48A828469905273802134AB697AF73835420F8736A917ACCAEA2F0884CBD1443
https://main.d3mbd42yfy75lz.amplifyapp.com/#/tx/48A828469905273802134AB697AF73835420F8736A917ACCAEA2F0884CBD1443

Seems like a problem with the first transaction. Bad node? Let me know if more testing is needed.

My BNB Address: bnb1w2y2afmeexmnhkktl9a8ewcsu62ejx5ry8hccx

**Comment by stuartkuentzel** [comment]
just tested, was able to swap native RUNE -> BTC. could've been a number of things as it's testnet and we've updated out BTC API provider since then. if it occurs again, feel free to open up another issue.
