### ISSUE TITLE
when swap Rune to BNB no blockchain explorer 

### ISSUE THREAD

**Issue by Jaxxou** [asgardex/asgard-exchange#116]
no blockhain explorer click appeared when you make a swap Rune to BNB

![no  view transaction](https://user-images.githubusercontent.com/78721473/107464311-76022900-6b79-11eb-903c-ee40840c0907.JPG)

must go on pending transaction to get the link for the block explorer 
https://main.d3mbd42yfy75lz.amplifyapp.com/#/tx/3894298485C47BE9B6FAB8F2E8A7EA956761CD0D75AA5ECFA74C3F7D185BF0A7

bnbadress
bnb16g22ty7974vsez06phd5hy6ulwx7zkctzy8sds

**Comment by stuartkuentzel** [comment]
fixed in https://github.com/asgardex/asgard-exchange/commit/0b091d407191c0a15c031d44ea8e37d060c15747
