### ISSUE TITLE
Rune price is not consistent between swaps and pools in ASGARDEX

### ISSUE THREAD

**Issue by ahmaban** [asgardex/asgard-exchange#117]
Hello Team, 

**I Have tRune on Testnet wallet for Asgard. When I check the price for swapping, I get the value below. 

Rune = 4.399 USD**

![image](https://user-images.githubusercontent.com/27192153/107549742-9ff33400-6be9-11eb-8188-01e176124a41.png)

**However, this is not the same value I have for tRune on my pools. 

Rune = 0.0153 USD**

![image](https://user-images.githubusercontent.com/27192153/107549677-8fdb5480-6be9-11eb-8c33-f19fadd8be6e.png)

Rune Address: tthor1agl6rszw08x4c9r049w84epku0kjg73yruy9k4

**Comment by stuartkuentzel** [comment]
Closing as this is related to THORChain testnet pools, not the asgard.exchange UI.
