### ISSUE TITLE
transaction not found on tbtc explorer

### ISSUE THREAD

**Issue by Jaxxou** [asgardex/asgard-exchange#118]
Hi everybody ! 

i add liquidity on the btc/rune pair, it works good but we can't see the transaction on the btc explorer : 

https://main.d3mbd42yfy75lz.amplifyapp.com/#/tx/80930ABA98C34696BBF70B78FF24C5218F03DEC47013FBA7BD9B54B25CE72949

https://blockstream.info/testnet/tx/583E746A6214334F7D8FD8524607FB771C95838E6F66419F4193C478FAEBC977

tthor1dqj9w9k39659h8dkrnn05teqwnfe87l5zf38hh
tb1q904end4dgelu4xusal42q8u4rwe0klqqs5r4dp

bnbadress
bnb16g22ty7974vsez06phd5hy6ulwx7zkctzy8sds

**Comment by stuartkuentzel** [comment]
Hey @Jaxxou thanks for this. We've recently updated the way pending transactions are show, you can take a look at the commit https://github.com/asgardex/asgard-exchange/commit/0b091d407191c0a15c031d44ea8e37d060c15747. Closing for now, but if you notice it again, feel free to reopen or file a new issue.
