### ISSUE TITLE
Add a link to token explorer

### ISSUE THREAD

**Issue by agomezrodriguez** [asgardex/asgard-exchange#119]
When clicking on User Settings, it would be nice to have a link to each token explorer plattform like etherscan for ERC20 tokens, blockchain.com for BTC or viewblock for RUNE.

**Comment by stuartkuentzel** [comment]
This is kind of tucked away, but exists. In User Settings, if you select a chain, next to "{CHAIN} Address" there's a little logo that brings you to an external explorer. For example, in the image below, it's the little icon next to "BNB Address".
<img width="418" alt="Screen Shot 2021-03-01 at 11 40 13 AM" src="https://user-images.githubusercontent.com/11183054/109445534-21204700-7a83-11eb-946d-65a92c519648.png">
