### ISSUE TITLE
incorrect amount of asset accepted

### ISSUE THREAD

**Issue by SLjavad** [asgardex/asgard-exchange#120]
i sent "-1" Rune  and it sent successfully

![4](https://user-images.githubusercontent.com/24592212/107877649-ff4f8d80-6ee2-11eb-9a63-e4dd909ccad7.jpg)

and the result : 

![5](https://user-images.githubusercontent.com/24592212/107877671-20b07980-6ee3-11eb-9677-c72c4cf42c70.jpg)

also in deposit when we don't enter anything .. panel doesn't show any warning or errors and we can submit:

![6](https://user-images.githubusercontent.com/24592212/107877753-87ce2e00-6ee3-11eb-90b2-fae12a7bc0de.jpg)

result : 

![2](https://user-images.githubusercontent.com/24592212/107877758-94eb1d00-6ee3-11eb-8af3-86f6dd575687.jpg)

**Comment by stuartkuentzel** [comment]
@SLjavad thanks for raising these, both issues need to be tightened up
