### ISSUE TITLE
failed submitting transactions

### ISSUE THREAD

**Issue by vacioincordio** [asgardex/asgard-exchange#121]
Been trying to buy btc with rune for several times. transactions fail and about .04runes are substracted from account at every attempt
![Failed tx rune btc](https://user-images.githubusercontent.com/27200867/107952333-ece45b00-6f99-11eb-8743-ffe62c57bf79.png)
![Failed tx rune btc 2](https://user-images.githubusercontent.com/27200867/107952392-fe2d6780-6f99-11eb-99e6-11ae7a6f32d1.png)

**Comment by facuardila** [comment]
same problem here, I tried to swap to BTC and BUSD and keeps failing, 

> "something went wrong submitting your your transaction on the network. your transaction has been refunded"

No problems swapping with BNB 

<img width="433" alt="Screenshot 2021-02-16 at 13 53 31" src="https://user-images.githubusercontent.com/18333425/108066031-187d4900-705f-11eb-8f29-36c53ee4b48a.png">

**Comment by stuartkuentzel** [comment]
@vacioincordio @facuardila if this is still happening, please send over associated tx ids. otherwise there's no way to trace what's going wrong.
