### ISSUE TITLE
ETH balance not shown after receiving funds

### ISSUE THREAD

**Issue by agomezrodriguez** [asgardex/asgard-exchange#128]
Performed a send transaction via Xdefi to My ETH testnet address https://rinkeby.etherscan.io/address/0x2e573cb1534df3e19ad6a0fa8b3c9cc54b70bf3d and balance is not shown in Asgardex.

<img width="430" alt="Captura de pantalla 2021-02-25 a las 10 02 23" src="https://user-images.githubusercontent.com/2371150/109129117-91ac2880-7750-11eb-9bbb-aac51d921f3f.png">

**Comment by stuartkuentzel** [comment]
ETH Testnet is on Ropsten, which is why funds aren't showing. ETH testnet network should be displayed in the UI.
