### ISSUE TITLE
Pooled Liquidity Vanished Without A Trace

### ISSUE THREAD

**Issue by fbpmot** [asgardex/asgard-exchange#129]
After checking my pooled liquidity, which included roughly 2000 Rune (1000 each) paired with BTC & BNB, every day to measure its progress. The Asgardex page now just says "No deposited pools found". I haven't done anything with those funds but sit and watch it accrue interest from fees. I know its just a testnet but its still a bit upsetting that all my Rune just disappeared off the network out of nowhere. Even trying to check any type of block explorer has mostly just lead to error messages or if my addresses are found it says that they haven't made any transactions. Now I'm having second thoughts about using the mainnet when it launches. If that had been actual Rune it would've been worth almost $10,000 (not including the pooled BNB & BTC). So some kind of explanation would be nice.

tthor1g5qtkzp59gwjcm3fjc74wrxa8dy5stu0atc3d0
tb1qcqe6dcpmrhpkk0qjpn89walsd54q4mnja6qrgd
tbnb1hchvdhlkwaeeehlvy2ylw6zh8v703sxtvu2ujn

**Comment by pistolstamen** [comment]
Same here

**Comment by stuartkuentzel** [comment]
There has been a bunch of updates to the multichain testnet this week, you can follow along on the dev telegram. Sometimes when they do a reset on testnet, all transactions and pooling are reset. Checking those addresses on midgard, they all look to be empty, so I assume that's what happened. Closing as this is more of a "THORChain" issue than an asgardex issue, but feel free to bring it up on the THORChain dev telegram thread if it's concerning.
