### ISSUE TITLE
No Test Rune Balance on BNB address - Asgardex

### ISSUE THREAD

**Issue by cajoca3** [asgardex/asgard-exchange#138]
Hello,

I've registered on Asgardex Testnet and following the instructions on this video https://www.youtube.com/watch?v=wihC9cAoItg , I tried to get some Test Rune from the RuneFaucetBot on Telegram.

Everything seem successful, as recorded on the BNB explorer transaction 9F5872C30182E7F76EF5D639B4608546B069E64F9109E75486B6D52867338924 as you can see on the screenshot
![image](https://user-images.githubusercontent.com/77206595/110212790-11469f80-7e95-11eb-829f-bcc501d2b981.png)

Though, on Asgardex, the BNB balance only shows the 0.009625 (0.01 - fee) and No Rune is there.
![image](https://user-images.githubusercontent.com/77206595/110212938-a34ea800-7e95-11eb-84a9-1cc13711bc02.png)

Can you please have a look at this, before we go to Mainnet, to fix any issues I might have on the Asgardex wallet before we start?

Thank you.

Carlos

**Comment by stuartkuentzel** [comment]
Is this an issue of refreshing the balance (in the top right)? The wallet don't constantly scan for external transactions, ie receiving funds.

Tested a wallet on my end, and all BNB funds are listed, including BNB.RUNE.

If it's still an issue, let me know how I can try and replicate the issue.

**Comment by cajoca3** [comment]
No. Refreshing the the balance only shows me what's on the previous screenshot I've sent. (0.009625 BNB, no Rune)

It should display this:
![image](https://user-images.githubusercontent.com/77206595/110781280-9e0aa800-825d-11eb-92b1-2fda78fd369a.png)
as per video on youtube, explaining how to get the test.rune from faucet.

However, the TxID 9F5872C30182E7F76EF5D639B4608546B069E64F9109E75486B6D52867338924 shows the transfer of bnb and Rune to the same asgardex test wallet `tbnb16cv0guhklktra8zg9g9kgh4cet4jctdfwgald2`

Is there any explorer to see these test transactions??

**Comment by stuartkuentzel** [comment]
Checking the binance testnet explorer -> https://testnet-explorer.binance.org/address/tbnb16cv0guhklktra8zg9g9kgh4cet4jctdfwgald2. It only shows BNB, you don't have RUNE in that wallet.

The highlighted message means that you need to upgrade your BNB.RUNE to THOR.RUNE. There is now native RUNE, THORChain doesn't use BNB.RUNE for pooling anymore.
