### ISSUE TITLE
Cannot add eth USDT liquidity to pool

### ISSUE THREAD

**Issue by Edv-Ester** [asgardex/asgard-exchange#139]
This following transaction on ThorChain was suppose to give me 1 Usdt on the Eth net.
https://main.d3mbd42yfy75lz.amplifyapp.com/#/txs/8AF457B239F7A724CF7D516FBCC79C443BD4C47B0D237A3C038248D5E75E4C96

When I got 2.39? The estimate was a little off. In testing for correct values, well perhaps?

Still, when I got to adding Usdt (Eth) liquidity to the pool..? I had no Usdt Eth in my balance? No less, the Usdt Eth shows up in the Eth wallet address?

Try and reproduce this issue. Swap some faucet Rune for 1 usdt from the eth net. Receive the swap and find it in the Eth wallet address. Try to add it to the liquidity pool..?

Bnb address: bnb1kzev5agwa5affrzlr8ut9jyxj8rqzsp4s6s847

**Comment by stuartkuentzel** [comment]
I wasn't able to replicate this exactly, but did add a check for sufficient eth in deposits, perhaps that was the issue. closing for now, if it's still an issue, feel free to open again or create a fresh issue.
