### ISSUE TITLE
Creating New Pool with ERC20

### ISSUE THREAD

**Issue by boxofscraps** [asgardex/asgard-exchange#148]
Ropsten DIA and RUNE were attempted to create a new pool. The minimum 1000 Rune required was reached but approve button still does not work.
![image](https://user-images.githubusercontent.com/15699137/110454694-6690d580-807c-11eb-9e2b-82c0dcbefb9d.png)

**Comment by boxofscraps** [comment]
Error was caused by no ETH in Ethereum address. Recommend a popup that warns users that ETH/ERC20 transfers require minimum ETH balance.

**Comment by stuartkuentzel** [comment]
@boxofscraps nice catch, this was happening in all places where contract approval was necessary.
https://github.com/asgardex/asgard-exchange/pull/155 closes this.

**Comment by boxofscraps** [comment]
bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f
