### ISSUE TITLE
Thor eth chain swaps

### ISSUE THREAD

**Issue by Edv-Ester** [asgardex/asgard-exchange#151]
Swap 2.0231664 rune for 1.00000009 Thor (eth chain)
https://main.d3mbd42yfy75lz.amplifyapp.com/#/txs/7EFECDC9603DEDDFD3974D97848A1659DEA3EB3DC05691A1046CA81CE6C8E06E

That transaction is still pending. 
Attempted another swap 0.002346355 BNB for 1.00000278 Thor
https://main.d3mbd42yfy75lz.amplifyapp.com/#/txs/BC550EED2375FD1E60384A656FE382E9EE1A424B672CFBFA475C7D3790802ECB

Both transactions haven't completed the swap for the Thor (eth chain)
There was a mention in the recent weekly development update about the eth bugs?

Bnb address: bnb1kzev5agwa5affrzlr8ut9jyxj8rqzsp4s6s847

**Comment by boxofscraps** [comment]
Swaps are successful now. Probably just took a little time

**Comment by stuartkuentzel** [comment]
Closing as this has more to do with the THORChain network itself than this repo. Keep in mind the transaction needs to process on both THORChain + external network, for example Ethereum, which can take some time.
