### ISSUE TITLE
WETH/RUNE Pool

### ISSUE THREAD

**Issue by boxofscraps** [asgardex/asgard-exchange#177]
We might want to refund WETH/RUNE pools similar to how RUNE.ETH/RUNE is not an allowed pool.  

https://testnet.thorchain.net/#/txs/19CAE2F5032203C700514A8627EACDD55ED027AEB1588E13AF0A1742AE61F726

**Comment by stuartkuentzel** [comment]
Chatted with a core dev who said having a WETH pool is a non-issue and will be treated like any other erc20 token. Closing out for now.

**Comment by boxofscraps** [comment]
Sounds good. Just wanted to make sure.
bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f
