### ISSUE TITLE
BNB add custom tokens

### ISSUE THREAD

**Issue by boxofscraps** [asgardex/asgard-exchange#179]
Custom tokens on the BEP2 cannot be added to the wallet or create pool. The add custom token is available for ethereum wallet for ERC-20. 

![image](https://user-images.githubusercontent.com/15699137/112437144-dbfad800-8d03-11eb-8f02-a745203375c7.png)

**Comment by stuartkuentzel** [comment]
This is how the APIs are built. Basically, any coins in your BNB wallet should automatically populate. In ETH, you need to explicitly search them.

So if you send yourself a BNB token, you won't need to manually add it, it'll just show up.
