### ISSUE TITLE
[UI] show approve button for add ETH liquid

### ISSUE THREAD

**Issue by momodaka** [asgardex/asgard-exchange#194]
Step
1. In Add Liquidity
2. Choose `THOR` will show approve button
![image](https://user-images.githubusercontent.com/30197937/112874778-ecd98e00-90f5-11eb-83e8-d875b8f37174.png)

3. Change `THOR` to `ETH`, approve button not hide
![image](https://user-images.githubusercontent.com/30197937/112874839-febb3100-90f5-11eb-8faa-1719b17b9093.png)

expect： not show approve button for ETH

**Comment by stuartkuentzel** [comment]
@momodaka thanks for reporting this, nice catch
