### ISSUE TITLE
UI interface not centered

### ISSUE THREAD

**Issue by hxro1** [asgardex/asgard-exchange#204]
Just noticed that when I connect the wallet , the swap interface isn't centered (Using Safari on MacBook Air). Then if I just scroll down for make it looks at the centre , when I swap , on the blurred background at the bottom , appear an ugly white band...
<img width="1440" alt="Screenshot 2021-04-01 at 11 36 54" src="https://user-images.githubusercontent.com/81752322/113286013-ea408980-92eb-11eb-99c4-421f59b96f8a.png">
<img width="1437" alt="Screenshot 2021-04-01 at 11 38 29" src="https://user-images.githubusercontent.com/81752322/113286035-f0cf0100-92eb-11eb-81ca-65acab392d77.png">

**Comment by stuartkuentzel** [comment]
Hey @hxro1 thanks for bringing this up, it hasn't been battle tested on Safari.
