### ISSUE TITLE
Successfully staked BTC-RUNE liquidity pair, but not showing in pool

### ISSUE THREAD

**Issue by MendoCrypto** [asgardex/asgard-exchange#210]
I upgraded the BNB RUNE to native RUNE, then swapped some for BTC and attempted to stake the BTC-RUNE lp... transaction pending... then not pending... funds are gone, but my liquidity is not showing up in the pool tab. 

***update: just took another few minutes to update, but now my staked testnet liquidity is showing! :) I'm stoked on this guys

**Comment by stuartkuentzel** [comment]
yeah, it can take some time due to whatever blockchain (ie btc can be a little slow sometimes). closing this out, glad it's showing up for you.
