### ISSUE TITLE
Seed phrase funnel upon keystore creation

### ISSUE THREAD

**Issue by vanaheimex** [asgardex/asgard-exchange#218]
Proposing an improved experience to assure users save their seed phrase immediately after keystore creation. We were asked to create this issue. Here's the proposed UX:

1) User creates the keystore.

2) Browser saves the file locally / asks the user where to save the keystore file.

3) User gets redirected to the seed phrase view with the seed phrase showing + asking the user to save the seed phrase offline, in the same order shown to him. The user has no ability to "exit" this view. He's forced to save the seed phrase and press a "I saved the seed phrase" button. He cannot use the ASGARDEX interface until he's gone through this funnel.

4) User presses "I saved the seed phrase".

5) User gets redirected to a view asking him to re-enter the seed phrase in the order it was showed to him last. He's given options of words (scrambled), and he must select them one by one until he re-enters the seed phrase in the proper order. Once he's done, he presses a validate button which confirms that he entered the seed phrase correctly. If he didn't enter it correctly, some error reporting highlights that it was incorrect, and asks him to restart. He can always go back to see what the seed phrase was if thinks he saved it wrong.

6) Once he's done again, he presses a validate button again If the seed phrases matches, he's told that he succeeded in saving the seed phrase, and can proceed to use the remainder of the interface.

**Comment by stuartkuentzel** [comment]
Closing this to break it into sub tasks.
https://github.com/asgardex/asgard-exchange/issues/220
https://github.com/asgardex/asgard-exchange/issues/221
