### ISSUE TITLE
Slip fees easily exceeded

### ISSUE THREAD

**Issue by aang0203** [asgardex/asgard-exchange#225]
![Screenshot 2021-04-08 at 12 41 25 PM](https://user-images.githubusercontent.com/82150468/114020714-cb9c3e80-9867-11eb-98f4-7307d60794d0.png)

**Comment by stuartkuentzel** [comment]
Hey @aang0203, this has more to do with the nature of the testnet pools than the UI itself. Once mainnet launches and some real volume moves into the network, the slip should be much more reasonable. Either way, thanks for creating an issue, and if you notice anything else feel free to open another issue.
