### ISSUE TITLE
Forward Explorer issues

### ISSUE THREAD

**Issue by skyorion427** [asgardex/asgard-exchange#227]
https://github.com/thorswap/thorswap-finance-app/issues/19
https://github.com/thorswap/thorswap-finance-app/issues/20
https://github.com/thorswap/thorswap-finance-app/issues/21

**Comment by stuartkuentzel** [comment]
@skyorion427 thanks for forwarding. closing these out and moving to explorer repo https://github.com/Pusher-Labs/thorchain_explorer
