### ISSUE TITLE
View Wallet Phrase

### ISSUE THREAD

**Issue by boxofscraps** [asgardex/asgard-exchange#228]
Wallet Phrase layout does not make it clear especially for newbies whether the words are down and across or across and down. Best to number the each word to prevent this confusion. 

![image](https://user-images.githubusercontent.com/15699137/114157929-05f1f400-98d9-11eb-90b5-38ff065facb8.png)

**Comment by stuartkuentzel** [comment]
@boxofscraps very true, doing a PR to add index indicators for the phrase
