### ISSUE TITLE
BCH Block Explorer 

### ISSUE THREAD

**Issue by boxofscraps** [asgardex/asgard-exchange#229]
Currently, the BCH block explorer for specific user address redirects to: https://testnet.asgard.exchange/

![image](https://user-images.githubusercontent.com/15699137/114158347-6bde7b80-98d9-11eb-8d4d-33b16a42e55e.png)

bnb1tar4mxlh4cpc0jvs8yg692uew40h8ddrna9g3f

**Comment by stuartkuentzel** [comment]
hey @boxofscraps thanks for reporting this, merging in a PR to resolve this
