### ISSUE TITLE
Stuck transaction swapping btc to rune

### ISSUE THREAD

**Issue by vaticanvoodoo** [asgardex/asgard-exchange#254]
I submitted a swap from btc to rune and the transaction has been stuck.  I can see the transaction in the bitcoin block explorer as "unconfirmed" and nothing is displayed in the THORChain block explorer.  Apparently the default gas fees were set to low.  What happens now?

**Comment by vaticanvoodoo** [comment]
My funds were just refunded but the issue still remains on stuck transactions.

**Comment by stuartkuentzel** [comment]
Hey @vaticanvoodoo, earlier today we merged a PR to fix the low gas rate bug, but it doesn't help pending transactions. 
It's being tracked https://github.com/asgardex/asgard-exchange/issues/265.
We're working on a way to speed up pending transactions.

**Comment by stuartwk** [comment]
Closing this as PR was merged to fix this and it seems funds were returned. Feel free to open another issue if you're still experience bugs.
