### ISSUE TITLE
Failed swap request & liquidity add

### ISSUE THREAD

**Issue by tylerleec** [asgardex/asgard-exchange#256]
I attempted to swap BTC for ETH. I was debited the BTC but never received any ETH to my ETH wallet. 

I never received the returned eth to my eth wallet. Even though the btc transaction shows many confirmations.

![image](https://user-images.githubusercontent.com/72435018/114588751-dfff8300-9c3b-11eb-8799-738de02e9f3a.jpeg)

I also attempted to add liquidity to the RUNE:BTC pair. Both assets were debited from my wallet. The native RUNE vanished and native BTC is still showing unconfirmed for over 3 hrs now.

![image](https://user-images.githubusercontent.com/72435018/114589239-569c8080-9c3c-11eb-9a9e-aa8ffd505f3d.jpeg)

These two TX show incoming RUNE. But never outgoing. 

![image](https://user-images.githubusercontent.com/72435018/114588339-70899380-9c3b-11eb-9154-2a80e8981edf.png)

**Comment by stuartkuentzel** [comment]
hey @tylerleec, would you mind sharing some of the corresponding txids or addresses for these transactions? it'll make it much easier to track down.
it sounds like you've hit on a number of issues. 
there is a known bug regarding BTC where the gas rates were off, so BTC transactions were stuck pending, I'm not sure if it's a result of that. there was a fix merged for that, but it doesn't free up currently pending transactions. https://github.com/asgardex/asgard-exchange/issues/265

**Comment by tylerleec** [comment]
The BTC to ETH swap was a small transaction so that may have been eaten up by gas fees. My bigger issue is the RUNE:BTC liquidity add. I wasn't given a THOR TxID for the pool add. Yet my native RUNE & BTC was still debited. 

HERE IS THE only TxID I was given for the BTC add. 

ff199d79e99496097a2d001e8cca9b4282199f2b56fb57dff55a7a564c17df78

**Comment by tylerleec** [comment]
I also just tried doing a swap of BNB>BTC. I received a way smaller amount of BTC than I was quoted. Something doesnt seem right. Im going to stop interacting with Asgard.exchange until big issues like this get sorted out. I know its not the BTC fee, I should still have 0.0011635 BTC after the 0.0003975 BTC FEE.

![BNB2BTC_missing BTC](https://user-images.githubusercontent.com/72435018/114795606-ccd7da80-9d43-11eb-91b1-88a49aced4ab.jpg)

BNB TxID : 31C92B10EFDF2D9329696DB4963E5E82D9934A7AA1B993C1C6E3330223B0C169

BTC TxID : 0b6e0578aff263aab43d8e10563e52fe3f9827ca1482ef2699d0328fc8dc8b60

**Comment by stuartkuentzel** [comment]
Hey @tylerleec, from the above screenshot, it looks like you're using the THORSwap app, which is actually a different codebase than app.asgard.exchange. You can find the THORSwap repo at https://github.com/thorswap/thorswap-finance-app/issues. 

Just keep in mind, THORChain multichain has just been released, it's called "chaosnet" because it can be kind of hectic. Swapping large amounts on any of the interfaces is discouraged at the moment, as pools can be imbalanced and bugs are being worked out.
