### ISSUE TITLE
minimum received is not what you get.

### ISSUE THREAD

**Issue by darrynrb** [asgardex/asgard-exchange#257]
I swapped native rune for usdt (erc 20) twice, both times the amount it said I would receive as a minimum was way off what I actually received.

The image below shows I should have swapped for 123 usdt (with a minimum of 117) but I only received 50.

![thor](https://user-images.githubusercontent.com/82465588/114590312-80779680-9c80-11eb-97cd-952054502d4d.jpg)

**Comment by stuartkuentzel** [comment]
hey @darrynrb 👋  thanks for testing out THORChain. This is actually the repo for the interface app.asgard.exchange and it looks like you're trying out Thorswap. I've forwarded it along to their dev, and it looks like they just opened an issue for it on their repo, which is linked above.
