### ISSUE TITLE
Total deposit to btc/rune pool is not reflected properly

### ISSUE THREAD

**Issue by vaticanvoodoo** [asgardex/asgard-exchange#260]
I swapped btc to rune in two batches, then added it to the btc/rune pool, but the pool only shows roughly half of the total that was sent to the pool.  See the below screen shots.

<img width="680" alt="Screen Shot 2021-04-13 at 5 07 47 PM" src="https://user-images.githubusercontent.com/37843387/114628142-080ed680-9c7c-11eb-8f71-a2990bdecfb6.png">

<img width="374" alt="Screen Shot 2021-04-13 at 5 10 39 PM" src="https://user-images.githubusercontent.com/37843387/114627637-30e29c00-9c7b-11eb-89eb-926f8a2018c8.png">

**Comment by stuartkuentzel** [comment]
hey @vaticanvoodoo 👋 , it looks like you're testing out THORSwap, which is a different interface. I passed the issue onto their dev, and it looks like they created a fresh issue for it on their repo, which is linked above.
