### ISSUE TITLE
Funds stuck while LP in the BTC pool

### ISSUE THREAD

**Issue by amanya** [asgardex/asgard-exchange#264]
Tried to LP, funds got removed from my wallet but then got stuck

Here is my thorchain address: https://thorchain.net/#/address/thor1ylf36zg4tztsrg82e5nzcac7elzhprdwps9aum

And my btc one: https://blockstream.info/address/bc1q3mae8gjsztryrqn0xde9d9rtr068lvc36kuhkk

Thanks!

**Comment by edwardjohansson** [comment]
It's the bitcoin transaction that you're waiting for:
https://www.blockchain.com/btc/address/bc1q3mae8gjsztryrqn0xde9d9rtr068lvc36kuhkk

They have unfortunately set the fee too low for LP transactions on bitcoin. Hopefully will be sorted soon.

More info in https://github.com/asgardex/asgard-exchange/issues/265

**Comment by amanya** [comment]
Yeah I suspected that, I'll wait for it, thanks!

**Comment by edwardjohansson** [comment]
@amanya 
Try this
https://www.viabtc.com/tools/txaccelerator/
Enter your transaction hash (it is 64e28d62f3f1fc04e8b11a0e9f7b7b77e4057386952d053c473a4e9fb651f889 ) and click 'submit for free'.

They open up slots at the start of every hour for free acceleration (and it runs out of slots within a minute) - if you do it straight away at the start of a new hour you should get in.

Should be processed on the next block that their mining pool solves.

**Comment by adv-delivery-artifactory** [comment]
Thanks @edwardjohansson, will try that! :)

**Comment by amanya** [comment]
Thanks @edwardjohansson, will try that! :)

**Comment by edwardjohansson** [comment]
@amanya Quick update, it worked for me!! woo I'm now in the pool.

**Comment by amanya** [comment]
Yeah, for me too. Thanks! Closing the issue.
