### ISSUE TITLE
ETH inbound transaction always sends 0 ETH, swap consequently fails

### ISSUE THREAD

**Issue by xtrapower** [asgardex/asgard-exchange#267]
I tried swapping ETH for RUNE via https://app.thorswap.finance/swap/ETH.ETH_THOR.RUNE

I chose to swap 0.04768524 ETH but the ETH transaction that is injected always sends 0 ETH and consequently no swap happens.

Transaction:
https://etherscan.io/tx/0x47f35c33db8b30614cc62f1eeafc0de269f2ac9e8f54c2696716f9318d77e405
<img width="1093" alt="Bildschirmfoto 2021-04-14 um 11 35 13" src="https://user-images.githubusercontent.com/8515199/114689470-042f9280-9d16-11eb-97b7-9cbf7cf323e0.png">

**Comment by stuartkuentzel** [comment]
hey @xtrapower 👋 , it looks like you're trying out the THORSwap interface, which is a different interface than app.asgard.exchange. I forwarded the issue to their dev, and it looks like they opened an issue on their repo, which is linked above.
