### ISSUE TITLE
Adding asymmetrical BTC Liquidity

### ISSUE THREAD

**Issue by Maesech** [asgardex/asgard-exchange#270]
hi, Im adding 100% BTC (asymmetrical) on thorswap.finance (since in the desktop version I dont find a way to deoposit asymmetrical yet) and the transaction doesnt go through, i.e. keeps spinning , see attached screenshot. 

![Bildschirmfoto 2021-04-14 um 12 58 41](https://user-images.githubusercontent.com/11945871/114700340-b28d0500-9d21-11eb-9e7a-15a1374c980b.png)

**Comment by stuartkuentzel** [comment]
Hey, this is due to an error from the other day where BTC transactions were being submitted with very low gas rates, blocking up the system. The tx will eventually be refunded.

**Comment by stuartwk** [comment]
Closing this out, as thorswap.finance is actually a different codebase than app.asgard.exchange (we don't yet support asym pool deposits). Feel free to open an issue at https://github.com/thorswap/thorswap-finance-app/issues if this is still ongoing.
