### ISSUE TITLE
Fallback if RUNE Tx fails during deposit

### ISSUE THREAD

**Issue by stuartkuentzel** [asgardex/asgard-exchange#271]
If the source asset fails, it's in a try/catch, and RUNE is never submitted.
If the source asset succeeds, but the RUNE asset fails, it looks like the funds are lost, when in fact THORChain is just waiting on the RUNE deposit of a symmetrical deposit.

Create a fallback page for users if the RUNE deposit fails to try and resubmit the RUNE deposit

**Comment by 4n0nym1z3** [comment]
Hey, I saw that this got closed, so, based on the recommendation I saw in #273 I tried to make another small addition to the BUSD pool, and the TX went through for both the BUSD and RUNE this time. However, things are in a bit of a weird state now. It looks like what happened is that it just turned half of my BUSD from my _original_ funding amount into RUNE, in addition to the two extra, smaller deposits I made. Not a terrible outcome, really. I’m just HODLing more RUNE.

Just wanted to make it known here that that’s what people should expect to happen.
