### ISSUE TITLE
Rune not displayed after swap

### ISSUE THREAD

**Issue by Maesech** [asgardex/asgard-exchange#272]
I swapped BTC to rune and the Rune are gone i.e. not displayed. BTC amount accurately reduced.  Here the tx: 

https://thorchain.net/#/txs/12079f04a52e0ba4176907a076107420a2c6eb025fcacdd1a2d1657e78add577

Best,

**Comment by stuartkuentzel** [comment]
hey @Maesech 👋  would you mind checking the wallet again? BTC transactions take some time to process, and it says in the explorer that the transaction was a success?

**Comment by Maesech** [comment]
you're right. It appeared now! 
since the transaction tx was empty before and Rune didnt display, I thought it didnt work. 
All looks good now and I added rune-btc liquidity. 

Not it only shows rune in the liquidity, this might also be, because it needs a little more time to process:

<img width="405" alt="Bildschirmfoto 2021-04-14 um 14 34 28" src="https://user-images.githubusercontent.com/11945871/114710886-917ee100-9d2e-11eb-9f5b-7aabc5240f4f.png">

let me know if I can help/support you somehow. you guys do an amazing job

**Comment by stuartkuentzel** [comment]
hey @Maesech, glad the transaction went through for you. Regarding the "pooled asset" being empty, if you check https://thornode.thorchain.info/thorchain/pool/BTC.BTC/liquidity_providers and search your BTC address, you will see that you are successfully pooled. 
From the screenshot above, it looks like you're using the THORSwap app, which is actually a different codebase. If you're still having an issue, feel free to raise it at https://github.com/thorswap/thorswap-finance-app/issues.

**Comment by stuartwk** [comment]
Closing this issue as it seems resolved and funds eventually came through. If you are still experience problems, feel free to create a new issue.
