### ISSUE TITLE
drastically higher fees than thorswap

### ISSUE THREAD

**Issue by nighthoch** [asgardex/asgard-exchange#276]
![image](https://user-images.githubusercontent.com/37465733/114793700-d2332600-9d3f-11eb-941a-b51ab304b0ca.png)

i lost over 60$ on a failed transaction and the fees were astronomically higher on asgardex than thorswap. i wouldve just used thorswap but i couldnt get any transaction to go through on there

**Comment by edwardjohansson** [comment]
@nighthoch Thorswap and asgardex LP had a bug yesterday which resulted in fees being too low. Many people (including myself) had transactions stuck because miners would not process them. I had to manually get a 3rd party miner to prioritise the transaction. See https://github.com/asgardex/asgard-exchange/issues/265 .
Thorswap now has the correct fees for fast transactions.

**Comment by stuartkuentzel** [comment]
Thanks for opening this. Going to be working with THORSwap to make sure calculations across interfaces are the same.

**Comment by kuiper23** [comment]
Hi, I had a similar experience today. Got 2 quotes for virtually the same transaction and one ADex was much more expensive. 

The quote seemed to have a few more bugs, but maybe I'm making a noob error of some sort. This is what I'm seeing: 

 - the warning at the bottom of Asgardex's quote seemed to suggest that tx fees would be greater than the amount received. But this doesn't seem to be the case. Comparing the send amount (~$36) and receive amount (~$25)  suggests tx costs for this swap would be around $11, which is 44% of the output.

- Attempting to calculate the tx cost myself using the quoted network fee (0.0000225 BCH) and BCH's approximate cost at the time (~$890) suggest an entirely different and much smaller tx cost of $0.02.

![Screenshot 2021-04-27 205355](https://user-images.githubusercontent.com/81938165/116347703-8c477a80-a7a1-11eb-8bf0-48607329ba6e.png)
![Screenshot 2021-04-27 205332](https://user-images.githubusercontent.com/81938165/116347705-8ce01100-a7a1-11eb-90e0-17a5b0eea6d3.png)
