### ISSUE TITLE
Failed to add BNB/RUNE pair

### ISSUE THREAD

**Issue by yingyeo** [asgardex/asgard-exchange#281]
Hi, I tried to add LP for BNB:RUNE last night using Asgardex web, and received a notification that my BNB deposit was successful, but that the RUNE deposit wasn't. It allowed me to re-try adding, which I did, but it failed again. Over the next 8 hours, I tried re-adding the rune intermittently, but it continued to fail, I guess because deposits have exceeded the cap. 

I finally closed the original pop-up for adding to the LP, and now there doesn't seem to be signs of my attempt to add LP. My RUNE has stayed in my wallet, but my BNB is gone. However, the deposit isn't reflected in the Pools tab. I've checked the BEP2 explorer and it shows that my BNB has been transferred. out. 

This is the transaction hash for the BNB deposit: https://explorer.binance.org/tx/8AB1AC566485550532E835BD4CD8F7CAA0378ADD51389372937465374FA3AD46

**Comment by stuartkuentzel** [comment]
Hey @yingyeo 👋 , there was a discovered issue with the xchain-thorchain wallet library basically saying you have insufficient funds to deposit RUNE, even though actually have enough. You can check see in https://thornode.thorchain.info/thorchain/pool/BNB.BNB/liquidity_providers, if you search for your BNB address, you will find "pending_asset" contains the BNB amount sent, but "pending_rune" is 0, due to the failed tx.

Once xchain has been updated, we'll push that, and we are working on a UI to re-deposit your RUNE. Once that happens, you will appear in the pool.

**Comment by yingyeo** [comment]
Thanks Stuart. May I know when I should try and re-deposit? I saw the 
message below on the Telegram channel, wasn't sure if the re-deposit is 
supported already.


------ Original Message ------
From: "Stuart" ***@***.***>
To: "asgardex/asgard-exchange" ***@***.***>
Cc: "yingyeo" ***@***.***>; "Mention" 
***@***.***>
Sent: 16/4/2021 10:16:30 am
Subject: Re: [asgardex/asgard-exchange] Failed to add BNB/RUNE pair 
(#281)

**Comment by stuartkuentzel** [comment]
@yingyeo I will let everyone know on github issues and also post on Telegram, etc when the code is merged in.
We have a pull request ready for this, but there's a tiny issue with the Midgard API. We're waiting on that to be resolved, which should be next week.

**Comment by stuartwk** [comment]
Hey @yingyeo, could you please try using https://app.asgard.exchange/deposit-sym-recovery to withdraw the pending funds?
What's happening is, your funds are stuck waiting on a RUNE deposit. The WITHDRAW depends on RUNE, so you must have at least 3 RUNE in your wallet to do the WITHDRAW (don't worry, it won't use 3 RUNE, but there will be a small THORChain network fee). THORChain is currently has pools capped, so the RUNE deposit won't work. This allows you to withdraw your pending BNB. If you have a chance, please confirm funds are recovered from pending.

**Comment by yingyeo** [comment]
Hi Stuart,

Many thanks for your help. I've successfully recovered my funds using 
your suggested method.

Regards,
Scott

------ Original Message ------
From: "Stuart" ***@***.***>
To: "asgardex/asgard-exchange" ***@***.***>
Cc: "yingyeo" ***@***.***>; "Mention" 
***@***.***>
Sent: 20/4/2021 1:14:01 pm
Subject: Re: [asgardex/asgard-exchange] Failed to add BNB/RUNE pair 
(#281)
