### ISSUE TITLE
Withdrawing liquidity mask slider + enter an amount does not work properly

### ISSUE THREAD

**Issue by CoraxR** [asgardex/asgard-exchange#283]
Story: 
I connected my wallet on Asgardex. >>In the tab "Pool" - I see added liquidity (LTC.LTC) correctly. Then I tried "Withdraw">>On the new mask where I should select the amount for withdrawing there is bugs: **I can move slider up to 100% but the amount of each asset for withdrawing is not displayed below. The button below "Enter an Amount" does not work at all, so there is no way to withdraw on the Asgardex.**
see on the screenshot slider is on 100% but amounts not displayed

Current:
Slider position does not affect for amount values of the assets and button "Enter an amount" remains inactive.

Expected:
Amount of assets should be displayed according to slider position, 
e.g. position on 50% then half of amount for both assets should be displayed below, 
e.g. position on 100% then full amount for both assets should be displayed below
As soon as withdrawing amount was changed by using  slider for more then 0,  the button "Enter an Amount" should became active and turn to button "Withdraw"

Accounts:
ltc1qlzquu7e9d4nrenr2un08w0prqvk560zdp96d7g
thor1amgpjp5rc2m6828p8rczn9nusypxaum80vgj5k
Pool:
LTC.LTC
Liquidity was added asymmetrically 
{
        "asset": "LTC.LTC",
        "asset_address": "ltc1qlzquu7e9d4nrenr2un08w0prqvk560zdp96d7g",
        "last_add_height": 69735,
        "units": "729270154",
        "pending_rune": "0",
        "pending_asset": "0",
        "rune_deposit_value": "638482818",
        "asset_deposit_value": "37682889"
    },

![Screenshot from 2021-04-16 23-59-39](https://user-images.githubusercontent.com/59896330/115096862-614e6280-9f27-11eb-88b2-bf15fe98aae8.png)

**Comment by stuartkuentzel** [comment]
Hey @CoraxR 👋 , thanks for bringing this up. At the moment, the UI only supports symmetric pool deposits, so it's not handling asymmetric withdraws. Asym deposits is something we're working on, should be available soon.

**Comment by stuartwk** [comment]
Closing this out, will work once asym deposits are added
