### ISSUE TITLE
failed BTC/RUNE Swap - Zero Balance showing

### ISSUE THREAD

**Issue by ellis1884** [asgardex/asgard-exchange#294]
Swapped BTC for RUNE, on both web and app, BTC balance deducted but I have not nor can I see any transactions or RUNE in the wallet(s) saying Zero assets.

address - thor1gurz0zxf77j8mu0ft7sapszlsydyekdl5mcpg2

**Comment by stuartwk** [comment]
Is this still an issue? Checking your THOR address, it says there's been a successful BTC -> RUNE transaction with a balance of about 17 RUNE https://thorchain.net/#/address/thor1gurz0zxf77j8mu0ft7sapszlsydyekdl5mcpg2

**Comment by ellis1884** [comment]
apologies for the delay, yes it finally showed up, it seemed like I had to manually toggle to the thorchain network then refresh for balances to show.

**Comment by stuartwk** [comment]
@ellis1884 thanks for the followup, closing out this issue 👍
