### ISSUE TITLE
0.02 BTC not refunded after failed add to LP

### ISSUE THREAD

**Issue by AmethystWizard** [asgardex/asgard-exchange#320]
Using app.asgard.exchange/pool

The application removed the cap warning and also removed the restriction that was in place for adding liquidity. 

I clicked to add liquidity to BTC/RUNE pool and there is no pending transaction. 
However, the balance of the pair depleted from my wallet. 
There is no way for me to track if this is happening or not and yet the value is gone.
The 'share of pool' balance has not proportionately increased to reflect the added liquidity I attempted to add.

**Comment by AmethystWizard** [comment]
Some amount appears to have returned to my wallet, but there is no way for me to determine if it's the correct amount. 
Liquidity was not added to the pool as was intended. 
There is no indication to the user as to why or what occurred.

**Comment by AmethystWizard** [comment]
To prepare for LP contribution I swapped 0.1 BTC ($5493) for BTC and RUNE in equal measure. 
Now after the two LP attempts I have 221 Rune ($3169) and 0.030 BTC ($1,576)
The sum amounts to a loss of $748 - ($4745 -  $5493)

**Comment by AmethystWizard** [comment]
My Thor Address:
thor1vnn5asakjkdmyw2s3y0wn3du5henuun6rz9u3w

**Comment by AmethystWizard** [comment]
The loss is actually more because I had some Rune in my wallet before making the LP attempt, the 221 Rune is a combined amount from my Rune balance before adding 0.1 BTC and after.

**Comment by stuartwk** [comment]
Hey @AmethystWizard, thanks for reaching out. Please contact @kkkilo on Telegram, and they will walk you through what to do from there.

**Comment by AmethystWizard** [comment]
KKKilo is an inappropriate and racist name. Is Thorchain misapropriating Norse mythology as a dog whistle to far right groups?
 
This issue is not closed.
