### ISSUE TITLE
Cannot swap ETH for RUNE

### ISSUE THREAD

**Issue by gitschwifty** [asgardex/asgard-exchange#321]
Attempting to swap ETH for RUNE through asgardex, definitely have enough to pay the gas fees but getting this error.

```
error making transfer:  Error: cannot estimate gas; transaction may fail or may require manual gas limit 
(error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit",
"code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR",
"body":"{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (17220)\"}}","error":{"code":-32000},
"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x22ecb25c00\",\"value\":\"0xa55d53a5a54a00\",\"from\":\"0x51546d4fe66e33778eefb45505a8d59f0ecad4e7\",\"to\":\"0x42a5ed456650a09dc10ebc6361a7480fdd61f27b\",\"data\":\"0x1fece7b40000000000000000000000001091c4de6a3cf09cda00abdaed42c7c3b69c83ec000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a55d53a5a54a00000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000373d3a54484f522e52554e453a74686f72316c7061356c33786c76676e7063686c76326c30686e74736e396d716876677837686e68706467000000000000000000\"}],\"id\":49,\"jsonrpc\":\"2.0\"}",
"requestMethod":"POST","url":"https://mainnet.infura.io/v3/c9cd2bfd3d164a12b70e4479167d4e22"},"method":"estimateGas",
"transaction":{"from":"0x51546d4Fe66E33778EEfb45505a8d59f0eCaD4E7","gasPrice":{"type":"BigNumber","hex":"0x22ecb25c00"},
"to":"0x42A5Ed456650a09Dc10EBc6361A7480fDd61f27B","value":{"type":"BigNumber","hex":"0xa55d53a5a54a00"},"data":"0x1fece7b40000000000000000000000001091c4de6a3cf09cda00abdaed42c7c3b69c83ec000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a55d53a5a54a00000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000373d3a54484f522e52554e453a74686f72316c7061356c33786c76676e7063686c76326c30686e74736e396d716876677837686e68706467000000000000000000","accessList":null}}, tx="[object Object]", code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.1.0)
```

I deposited more eth into my wallet today because I had been getting this before & thought it was an issue with gas fee calculation and not having quite enough for it (and why not, I'd get more rune that way), but this error is still occurring for me. Trying through thorswap isn't better, every time I try to put any amount in the from field, it resets to a single digit (i.e. I type 0.04, and the display goes 0 -> 0 -> 4, no decimal). 

I like what y'all are doing and obviously want to get some Rune, looked through closed issues and saw a couple others with similar errors, but I'm not trying to withdraw the ETH because Rune is not supported by any exchanges that I use. Any help would be appreciated, cheers!

**Comment by stuartwk** [comment]
hey @gitschwifty 👋 , this is an ongoing issue we're working on resolving. If you're trying to swap the max amount, you could be running into this. You can wait until a push is fixed or lower the amount you're trying to swap.

**Comment by gitschwifty** [comment]
hey @stuartwk thanks for quick response! I'll go ahead and close this then, I ended up using uniswap to swap to rune. If the fees should be similar between uniswap & asgardex, asgardex estimated the fee low by ~0.007 ETH at a gas price ~85 gwei
