### ISSUE TITLE
Pending BTC lost after withdrawing 100% of provision 

### ISSUE THREAD

**Issue by djesys** [asgardex/asgard-exchange#323]
After seeing my BTC as a "pending_asset" for days here:
https://thornode.thorchain.info/thorchain/pool/BTC.BTC/liquidity_providers

I followed instructions on how to recover them by withdrawing everything form the pool here: https://app.asgard.exchange/deposit-sym-recovery
It´s been more than 10h and nothing has changed. Jatin suggested to open a ticket here.
please advise.

**Comment by stuartwk** [comment]
Hey @djesys, a small update was pushed. Please try the deposit-sym-recovery again

**Comment by djesys** [comment]
I did the updated recovery about 8h ago and still no BTC in my wallet. 
Recovery is not seeing any more pending pools and under

https://thornode.thorchain.info/thorchain/pool/BTC.BTC/liquidity_providers

I can see my former pending BTC  aka "pending_asset" balance replaced by a much smaller amount, likely the fee.
Even more, I see no pending transactions on my btc address. Where are my btc ? 

Help much apreciated.

**Comment by djesys** [comment]
Hello Team!
Just a heads up that despite the fact that all nodes are now running 0.49.0, my missing funds have still not been credited.

This bugfix should have taken care of the issue.

https://gitlab.com/thorchain/thornode/-/merge_requests/1669

**Comment by djesys** [comment]
BUMP

**Comment by stuartwk** [comment]
The amount appeared as a "pending_asset" in liquidity providers for BTC. Talked with @djesys, they successfully withdrew using https://app.asgard.exchange/deposit-sym-recovery. BTC is back in their wallet. Closing this out.
