### ISSUE TITLE
BTC refunded and fee charged 

### ISSUE THREAD

**Issue by RUNEBeast** [asgardex/asgard-exchange#325]
I tried to add to btc pool on app.thorswap.finance 04/22/21  it did not show cap was full, I tried to add a couple times and transactions didn’t complete, was refunded each time.  After the transactions,  I looked at the details and realized I was charged about .01 btc for the 3 failed/refunded transactions.   My btc dropped from .3268 to  to .3178 .  My address is listed below:
bc1qy3uysxm9zfhzjtx47ahcstj9jxjl0vwzu2q463       Please help me get a refund and look into this issue.

**Comment by stuartwk** [comment]
Hey @RUNEBeast 👋 , this is actually the repo for app.asgard.exchange. Thorswap is a different codebase. You're free to open an issue with them at https://github.com/thorswap/thorswap-finance-app/issues. 

You can also DM `kkkilo` on Telegram regarding this issue.

**Comment by RUNEBeast** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
