### ISSUE TITLE
Feature request: Ability to adjust gas on send

### ISSUE THREAD

**Issue by anonfiveone** [asgardex/asgard-exchange#328]
I waiting over 2 hours for a send tx to send an erc20 to another wallet. It was due to the very low gas.

Would be nice to have the ability to adjust gas.

**Comment by stuartwk** [comment]
Hey @anonfiveone, this is kind of a xchain limit at the moment. You'll be able to adjust gas limit with XDEFI integration 👍

**Comment by anonfiveone** [comment]
That's very useful thanks
