### ISSUE TITLE
Cannot retrieve liquidity from the BTC pool!

### ISSUE THREAD

**Issue by JeremyVansnick** [asgardex/asgard-exchange#341]
I have created a new wallet a few days ago on https://app.thorswap.finance/, then I went on https://app.asgard.exchange/pool to pool a small amount of BTC's (no Rune, only BTC's).

**Now I am trying to remove the BTC's from the pool but it is not allowing me to do so.**

Here are 2 screenshots showing the situation:
![image](https://user-images.githubusercontent.com/23563794/116096004-3099c600-a6a9-11eb-9065-e3b4683a5396.png)
![image](https://user-images.githubusercontent.com/23563794/116096056-3d1e1e80-a6a9-11eb-8602-037ca748b701.png)

I set the withdrawal amount to 100% yet the button still shows "enter an amount"

Note that I currently have in my wallet the following:
- 0.03242599 BTC
- 0 Rune (No runes!)

I asked on the THORChain Community Telegram forum and they have directed me here, please let me know what's going on :)
Have a good day.

**Comment by stuartwk** [comment]
Hey @JeremyVansnick 👋. Would you mind sharing your BTC and THOR addresses that way I can take a look?

**Comment by JeremyVansnick** [comment]
@stuartwk Here they are.

BTC Adress: bc1q5pjqevcmdf7ng2kptn788mactmc7ja0f6ghgjk
THOR Adress: thor1cpar5z2dla54fa7mrjn926zq3aw4dwkzv9sh3y

**Comment by stuartwk** [comment]
Hey @JeremyVansnick, this is because it looks like you added liquidity using THORSwap as an asymmetrical deposit. AsgardEx is working on asym deposits (https://github.com/asgardex/asgard-exchange/issues/284), but at the moment you can only deposit + withdraw using sym deposits. You can withdraw your funds on app.finance.thorswap.

**Comment by stuartwk** [comment]
Asym withdraw support has been added, closing out this issue
