### ISSUE TITLE
Issues sistem swap

### ISSUE THREAD

**Issue by hadi2205** [asgardex/asgard-exchange#343]

**Comment by stuartwk** [comment]
Hey @hadi2205, could you please describe the issue you're encountering?

**Comment by stuartwk** [comment]
The midgard API went down today shortly after the cap was raised. Cap maxed out almost immediately. Swaps should go through, but adding liquidity may have been refunded. You can check if your deposit only partially went through at https://app.asgard.exchange/deposit-sym-recovery. Search the BTC pool. If there is a result, you'll be able to withdraw the funds.

**Comment by stuartwk** [comment]
Closing this out, feel free to reopen if you encounter other issues.
