### ISSUE TITLE
Follow on from issue 279

### ISSUE THREAD

**Issue by SirBenStokes** [asgardex/asgard-exchange#347]
Hello,

Perhaps I should have got back sooner so apologies, but the I don't think the recovery worked. The ''missing" RUNE doesn't appear to be back in my wallet and my attempted contribution to the liquidity pool also seems to still be showing as in screenshot 1

1
<img width="656" alt="image" src="https://user-images.githubusercontent.com/82573891/116207400-224ab900-a740-11eb-9259-616f7e45a459.png">

**Comment by stuartwk** [comment]
Hey @SirBenStokes, searching your BNB address in https://thornode.thorchain.info/thorchain/pool/BNB.BNB/liquidity_providers, it looks like you still have pending asset. An update was pushed to the sym deposit recovery page a couple days ago. Would you mind giving it another shot? Follow up if it succeeds or fails and we can work from there.

**Comment by SirBenStokes** [comment]
Hi @stuartwk. Ok I have given it another go. The missing deposit was found (screenshot 1), and I have submitted the withdraw request (screenshot 2)


I will give it 24 hours and come back to you. Thank you for your help.





1 - 
<img width="656" alt="image" src="https://user-images.githubusercontent.com/82573891/116243633-6e5d2400-a767-11eb-80da-2d685b1a1cda.png">


2 - 
<img width="656" alt="image" src="https://user-images.githubusercontent.com/82573891/116243758-92206a00-a767-11eb-991a-e9267bf38c1e.png">

**Comment by SirBenStokes** [comment]
Ok it looks like it has worked straight away this time.

Is it wise to try and deposit it right away (or as soon as the caps are increased)?

And just to be clear, when adding liquidity, I must add a balanced amount of both assets, i.e. I can not enter all my RUNE for example and let it swap/balance automatically?

Again, thank you very much with all your help and patience.

**Comment by stuartwk** [comment]
Glad it worked! Adding shouldn't be a problem once caps are increased, the bug should be resolved. Try it with a small amount first. The bug that created this was a problem with xchain-thorchain that failed the RUNE transaction, leaving the transaction in limbo. That bug has been resolved, so you shouldn't encounter the same issue. Closing this issue out, thanks for your patience with it.

**Comment by SirBenStokes** [comment]
Fantastic, thank you, appreciate all the help over the last two or so weeks.
