### ISSUE TITLE
ETH funds not showing in Asgard wallet

### ISSUE THREAD

**Issue by mthoma112288** [asgardex/asgard-exchange#350]
I sent ETH and ERC-20 RUNE to the ETH address providedded in my Asgard wallet and can see on Etherscan that the transaction went through successfully and the funds are in that wallet. However, this is not reflected on the Asgarddex site or wallet. It says I have no funds.

**Comment by stuartwk** [comment]
Hey @mthoma112288 could you please provide your ETH address so we can take a look?

**Comment by mthoma112288** [comment]
this is the ETH address within my Asgardex wallet where the funds were sent to 
0x0bd2d5f3383b9d163b8e9f59b95febf9f86882c0

**Comment by stuartwk** [comment]
hey @mthoma112288, sorry for the delay. Code has just been pushed to resolve this issue, give it another shot. Any other issues, feel free to open a new issue.
