### ISSUE TITLE
depositing rune from binance as bep2 token 

### ISSUE THREAD

**Issue by michaelalinskie** [asgardex/asgard-exchange#354]
i didn't; receive any runes after sending 9 runes to the bnb wallet address in asgard exchange 
ive waited 2 hours plus for it to show up 
what could go wrong, i tried sending to thor wallet in asgard but bep2 wont let me, and it only lets me send to bnb wallet address. 

pls help

**Comment by stuartwk** [comment]
Hey @michaelalinskie, would you mind sharing your BNB address, that way I can take a look.

BNB.RUNE should only be sent to your BNB address, otherwise it will be lost.

**Comment by michaelalinskie** [comment]
hi it's this one 

bnb1pdvs40guufm04yz7cvdup7te5z2xuxlz5l3rcy

**Comment by michaelalinskie** [comment]
i sent 10 runes but because of fees it becomes 9. xxx runes to bnb wallet at asgard ex

**Comment by stuartwk** [comment]
Great, it seems like you've received the RUNE. Everything looks to be working as expected?

**Comment by michaelalinskie** [comment]
hello Stuart, it shows here https://binance.mintscan.io/account/bnb1pdvs40guufm04yz7cvdup7te5z2xuxlz5l3rcy 

but it doesnt show at the asgard exchange 

https://app.asgard.exchange/swap

**Comment by michaelalinskie** [comment]
or do i have to send bnb there first ? to the bnb wallet .

**Comment by stuartwk** [comment]
Hey Michael, are you checking for the THOR.RUNE or BNB.RUNE? It's a little confusing, but there are different RUNE tokens, BNB.RUNE, ETH.RUNE, and THOR.RUNE. For multichain, the only thing you can really use in the system is THOR.RUNE for swaps and deposits. You can upgrade your ETH.RUNE or BNB.RUNE to THOR.RUNE by clicking the "Upgrade to Native RUNE" button on the top right on desktop. 

To find your BNB.RUNE, in the user settings, you'll have to click on the BNB section in the user settings area (not the THOR address).

If you're still not finding it, please send a screenshot of the user settings -> BNB address.

**Comment by michaelalinskie** [comment]
Im checking for the thor rune

I sent 10 thor but i cant send it to the thor wallet as it is not the right
format for bep2 address , binance said

I sent it to the bnb wallet in asgard exchange

**Comment by stuartwk** [comment]
Please check for BNB.RUNE in the BNB section of the user settings area. You have BNB.RUNE, not THOR.RUNE. The only way to get THOR.RUNE is to upgrade via AsgardEx or THORSwap. Native THOR.RUNE is not available through any centralized exchanges yet.

**Comment by michaelalinskie** [comment]
Ohh i see so i have bnb rune. Okay got it
But it is not showing
In the bnb wallet

**Comment by stuartwk** [comment]
Send a screenshot of the BNB wallet in user settings

**Comment by michaelalinskie** [comment]
![image](https://user-images.githubusercontent.com/62102121/116525772-0f341680-a903-11eb-9006-97de1b11bcee.png)
![image](https://user-images.githubusercontent.com/62102121/116525857-270b9a80-a903-11eb-8f43-64811ebe764d.png)

**Comment by michaelalinskie** [comment]
like this ?

**Comment by jcansdale** [comment]
@michaelalinskie,

It looks like your RUNE is here:
https://explorer.binance.org/address/bnb1pdvs40guufm04yz7cvdup7te5z2xuxlz5l3rcy

![image](https://user-images.githubusercontent.com/11719160/116686628-fb90ba80-a9ab-11eb-8dea-86a788160658.png)

You should be able to access this if you import your key phrase into something like Trust Wallet.

Alternatively you might be able to use BEPSwap to access BEP2 assets:
https://chaosnet.bepswap.com/connect

I don't know if Asgard and BEPSwap use compatible keystore files. I'm guessing @stuartwk would know.

**Comment by michaelalinskie** [comment]
thank you it's finally showing at the https://app.thorswap.finance/swap/
 it wasn't showing anything before. now i have to transfer bnb to upgrade the bnb rune to thor rune

**Comment by stuartwk** [comment]
@jcansdale yup compatible keystore files. Both use xchain. 
@michaelalinskie I'd still like to reach out via since this seems like an odd bug, your BNB.RUNE should be appearing in both interfaces.
closing this out as it seems resolved.
