### ISSUE TITLE
Keystore Login Incorrect

### ISSUE THREAD

**Issue by LaelLeeH** [asgardex/asgard-exchange#363]
Hi. 
I created an Asgard  wallet last night, and successfully transferred bitcoin into it.  This morning I am trying to access the wallet with my keyfile and password and I am getting the message Keystore Login Incorrect. 
I did move the keyfile to store it safely - will this be an issue?

**Comment by stuartwk** [comment]
Hey @LaelLeeH, moving the keystore file should have no effect

**Comment by LaelLeeH** [comment]
Hi Stuart - thanks. So how do I get back in - I know my password is correct but it is not being recognised

**Comment by stuartwk** [comment]
We don't have an "import phrase" feature yet, but https://app.thorswap.finance has this in place. Or try importing the phrase to Trust Wallet. As long as you have your phrase, funds are recoverable.

**Comment by LaelLeeH** [comment]
OK - it is probably gone then!  Newbie pain! Ouch! 

I have the file and I know my password - Is there not a way I can recover with those two?

**Comment by LaelLeeH** [comment]
I just tried to connect on  https://app.thorswap.finance  and I get the message - Not  valid json file - am I using the wrong file?

**Comment by stuartwk** [comment]
My guess is you're using the incorrect file. If you created the keystore on app.asgard.exchange, the filename would be something like `asgardex-thor...txt`. All interfaces are using the same library to create keystores (https://github.com/xchainjs/xchainjs-lib/blob/a8e98f79fc4137816dceca125e4f822438031447/packages/xchain-crypto/src/crypto.ts#L88). So your keystore should work on any existing interface. But interfaces can name the file differently. 

But `user.realm` and `wallet.realm` is not a keystore created on app.asgard.exchange.

**Comment by LaelLeeH** [comment]
OMG - serious newbie pain!  Can't find that file anywhere! Guess I will have to write it off and start again. Thanks for your assistance.

**Comment by stuartwk** [comment]
Super sorry to hear that, best of luck recovering your funds!
