### ISSUE TITLE
Can't convert Eth Rune to Native Rune

### ISSUE THREAD

**Issue by LaelLeeH** [asgardex/asgard-exchange#370]
Hi,
My wallet shows I have 5 ERC20 Rune that need converting to Native Rune
image

I don't think this next pic is correct. It shows my 5 Rune twice in my Eth account, and I'm sure it should only show once, but I might be wrong???
image

Then when I select either of them and click next to convert, I get this following message and it just hangs.
Message : "This RUNE is currently a ETH token. By clicking the button below, you will be upgrading it off of the ETH chain to native RUNE. Your native RUNE will show up in your RUNE wallet in user settings."
The blue circle just rotates - I never get any button to select.

image

Not sure if these screenshots are uploading - I hope so. Please help?

**Comment by LaelLeeH** [comment]
![image](https://user-images.githubusercontent.com/81672712/117423516-1b326080-af21-11eb-8f4a-28794a527599.png)

![image](https://user-images.githubusercontent.com/81672712/117423579-29807c80-af21-11eb-825a-449ed1e3d37f.png)

![image](https://user-images.githubusercontent.com/81672712/117423597-300ef400-af21-11eb-9b1d-740e5ba987a1.png)

**Comment by stuartwk** [comment]
Hey @LaelLeeH, we just pushed some code that updates in this area. Would you mind trying this again? Additionally, please make sure you have some ETH in your wallet in order to upgrade ETH.RUNE -> THOR.RUNE.

**Comment by stuartwk** [comment]
Closing this out, feel free to create a new issue if you run into this issue again.
