### ISSUE TITLE
Offline signing with a keystore wallet

### ISSUE THREAD

**Issue by crocket** [asgardex/asgard-exchange#377]
Offline signing achieves great security without reliance on hardware wallets.

In my theory, a password-encrypted keystore wallet can contain just a private view key, and a small command line wallet can create a full keystore wallet on an offline machine and export a view-only wallet from it. Asgard exchange can create unsigned transactions. The command line wallet can sign transactions offline. Asgard can broadcast signed transaction.

A few things to figure out in order to implement offline signing

* How keys are structured in a keystore wallet
* Where keys are used in asgard exchange
* How keys are constructed and used

I can help with development of a tiny command-line wallet dedicated to creating an offline wallet and signing transactions offline.

**Comment by stuartwk** [comment]
Hey @crocket 👋 , this is ambitious but a bit out of scope of our focus at the moment. We're looking to get other, more used wallets integrated, and I think command-line wallet would be pretty niche. 

That said, it's a cool idea, and I'm sure TC devs would love to have a tool where they can submit txs via command line. Could be worth pursuing as a separate project.

**Comment by crocket** [comment]
Do you suggest I take it to thorchain project?
