### ISSUE TITLE
Unable to trade as BCH output. Legacy address no long supported

### ISSUE THREAD

**Issue by BitHighlander** [asgardex/asgard-exchange#379]
It appears legacy BCH addresses are not longer supported. Will need to convert to cashaddr format. 

![Screen Shot 2021-05-13 at 11 55 42 AM](https://user-images.githubusercontent.com/4935895/118166226-71504980-b3e2-11eb-844f-5cc1e7d24acf.png)

Recreate:
Attempt any BCH output trades

**Comment by blitztrader24** [comment]
Same issue here had 2 swaps usdt for bch. Charging me $400 in gas and refund fees. Maybe disable for now? So other people won't have issues. 

https://thorchain.net/#/txs/f138276fbcd9c8e8292f236cc744790d658720c8ddd67759d1f1ea254ae2b18c

**Comment by stuartwk** [comment]
Thanks for bringing this up, temporarily disabled BCH

**Comment by stuartwk** [comment]
this should be closed with the xchain update https://github.com/asgardex/asgard-exchange/pull/394
