### ISSUE TITLE
ETH Transfer Not Showing In Wallet

### ISSUE THREAD

**Issue by mcdrama** [asgardex/asgard-exchange#384]
Deposited (3 days ago) 1 ETH from CB Wallet to Asguard Wallet (Etherscan shows successful)  - But my 1 ETH is still not showing available in Asguard - Please Help

**Comment by stuartwk** [comment]
Hey @mcdrama, this is actually an ongoing issue with ethplorer https://github.com/EverexIO/Ethplorer/issues/209.
Your funds are safe, but just not being recognized. You can try it in a few different UIs, or import your phrase into Trust Wallet to access your funds.
