### ISSUE TITLE
Sent ERC20 RUNE to ETH address

### ISSUE THREAD

**Issue by thatguy1466** [asgardex/asgard-exchange#387]
I sent some ERC20 RUNE to the ETH address in my asgard wallet. Was this a mistake? I can see it on etherscan but it doesn't show up in my Asgard wallet. If this is incorrect, since I own more ERC20 RUNE, how do I convert it to native RUNE?

**Comment by stuartwk** [comment]
Hey @thatguy1466, that's correct, sending ERC20 RUNE to your ETH address should work. We've had issues with the xchain api ethplorer dependency giving odd results. If it still isn't showing up in asgard exchange, feel free to share your eth address and I can look into it.

**Comment by stuartwk** [comment]
Closing this out, there have been some XChain updates merged since this issue was opened. Feel free to open a new issue if you encounter this again.
