### ISSUE TITLE
Issue trying to add liquidity to BNB/RUNE pool

### ISSUE THREAD

**Issue by Tuminha** [asgardex/asgard-exchange#388]
Hi there

A few days ago, I added some liquidity to BNB/RUNE pool, and everything worked ok. 

My surprise is today that I want to add more liquidity (RUNE and BNB), and I have enough funds, but the annoying "forbidden" symbol shows up on the BNB side of the pool, not allowing me to add further liquidity. 

Do I have to remove all my assets and add them again? 
<img width="1047" alt="Screen Shot 2021-05-24 at 10 47 14" src="https://user-images.githubusercontent.com/83960151/119322821-52717300-bc7e-11eb-8b19-156cec104ebd.png">

I really appreciate any help you can provide. 

PD- I also tried another liquidity pools (LTC) and again the 🚫 symbol appears when trying to add a value).

**Comment by stuartwk** [comment]
Hey @Tuminha, at the moment the pools are capped. You can follow along when caps are raised on the https://t.me/thorchain_org. Also, it looks like you're using the desktop app, which is actually a different codebase you can find -> https://github.com/thorchain/asgardex-electron.

**Comment by Tuminha** [comment]
> Hey @Tuminha, at the moment the pools are capped. You can follow along when caps are raised on the https://t.me/thorchain_org. Also, it looks like you're using the desktop app, which is actually a different codebase you can find -> https://github.com/thorchain/asgardex-electron.

Amazing @stuartwk ! Thanks a lot. I joined the discord and I could figure out that they are capped. Hopefully, in 24 hours we can join pools. Regards
