### ISSUE TITLE
Missing BNB after failed transaction to add liquidity

### ISSUE THREAD

**Issue by abcrypto30** [asgardex/asgard-exchange#391]
Hi Thorchads,

I tried to add liquidity to the BNB-RUNE pool.

Thor address: thor1z2x6tg0fzt26gwqudnwml3yzgfq6pdc5su8tee

BNB address: bnb1vlzve2kn8tncdjtxqxyg4aeyh33ycl0qskeupw

1. Converted RUNE to native RUNE
2. Tried to add liquidity to BNB-RUNE pool
3. Asgardex threw an error message "Insufficient funds" but my BNB got deducted from my wallet
But you can find this transaction on the Binance chain
<img width="1136" alt="Screenshot 2021-05-26 at 02 08 43" src="https://user-images.githubusercontent.com/57846705/119583887-daaf5f80-bdc7-11eb-933c-5bd4c6e73d26.png">

This transaction is also has my Thor address in its MEMO.

4. My BNB has been deducted from my wallet which does not show up in my pools.

Is there any way I can recover my lost BNB?

**Comment by stuartwk** [comment]
Hey @abcrypto30, this sounds a bit odd. You can take a look at your BNB transactions https://thorchain.net/#/address/bnb1vlzve2kn8tncdjtxqxyg4aeyh33ycl0qskeupw

I see there are 2 times you upgraded to native RUNE, and a successful deposit.
If there is something off, please send the link to the transaction and we can try and figure it out.

**Comment by stuartwk** [comment]
Found the tx you're referring to https://explorer.binance.org/tx/B31DDDAA306F472FCD77785EE5470170CC6B85DEAEBD4ABE84206F5E298E5709. Following up with the team.

**Comment by stuartwk** [comment]
It looks like the RUNE deposit failed. You can simply withdraw the pending BNB at https://app.asgard.exchange/deposit-sym-recovery. Search the BNB pool, and you'll have the option to withdraw and recover funds. Keep in mind, this will withdraw 100% of what you have deposited into the BNB pool (including previously successful deposits).

**Comment by abcrypto30** [comment]
Hey @stuartwk,

Thanks a ton for the help. Was able to recover my funds and added to the liquidity pool through https://app.thorswap.finance/ this time successfully.
