### ISSUE TITLE
Attempt to create a BNB.USDT pool failed - Funds not returned to the user.

### ISSUE THREAD

**Issue by bullishtrader** [asgardex/asgard-exchange#393]
Hey there, an user opened a ticket in the THORSwap support center with this issue:
Can someone help with this? Many thanks.

1. User tried to create a new pool (BNB.USDT-6D8) on asgardex.exchange. 

Adding 11,813.11844682 BNB.USDT-6D8 and 1,083.07262 RUNE.

The BEP2 transaction was executed (https://explorer.binance.org/tx/57DAABBD516E7954357B76393C4C9DC9343DB88FEABF6C2C3748B9DE893387A2)
The Thor transaction was not executed.

2. User tried to send the RUNE transaction again manually by modifying the MEMO.
https://viewblock.io/thorchain/tx/4EC5E2265CD5D20AC18B3FC22A9C20933B64E4633A3B93A23548C4E8701CD647
The transaction shows an internal error. The funds have remained in my wallet.

3. The 11,813.11844682 BNB.USDT-6D8 have not been refunded. According to docs "The asset that reaches THORChain first is put into "pending". It is not clear how long this assets remain pending.

4. Is there a way for the user to get refunded the 11,813.11844682 BNB.USDT-6D8 ?

5. Alternatively I could try again to send the missing RUNES (1000 shoud be enough) to get the pool staged.

In this case what MEMO and recipient would be needed. I tried with the following:

Memo: "+:BNB.USDT-6D8:bnb18xn670lz9fqaympue27a6lfnrjeptgrcrlxy3s"
Recipient: "thor1g98cy3n9mmjrpn0sxmn63lztelera37n8n67c0", I assume the recipient changes every couple days.

**Comment by stuartwk** [comment]
Hey @bullishtrader 👋 , following up. I saw this was mentioned on the discord dev server as well, not sure if it was you, but looked to be resolved on there. Are your funds still pending?

**Comment by gerigag** [comment]
Hey @stuartwk, the funds are still pending/in the pool address/not refunded.

This is the current Thorchain BEP2 pool address: https://explorer.binance.org/address/bnb198q247rpj2n9tzprf3z3j7khr273x7k65fl6gr
The 11,822.11844682 USDT are still there and therefore have not been refunded.

**Comment by stuartwk** [comment]
You are listed in liquidity providers with pending funds -> https://thornode.thorchain.info/thorchain/pool/BNB.USDT-6D8/liquidity_providers

We have UI to withdraw pending funds from existing pools, but not something for pending funds in a newly created pool. Will follow up with the team on why the RUNE tx has failed and best way to withdraw pending funds.

**Comment by bullishtrader** [comment]
> You are listed in liquidity providers with pending funds -> https://thornode.thorchain.info/thorchain/pool/BNB.USDT-6D8/liquidity_providers
> 
> 
> 
> We have UI to withdraw pending funds from existing pools, but not something for pending funds in a newly created pool. Will follow up with the team on why the RUNE tx has failed and best way to withdraw pending funds.

Thanks for following up this issue. Much appreciated.
If the funds will be refunded to the sender address withdrawing from the pool in some way, would be awesome.

The user is looking to add the liquidity again, once the funds are returned to his wallet.

Once again, thank you so much I'll keep following up this issue 😉

**Comment by gerigag** [comment]
@stuartwk 
I think resending the Thor transaction would be the easiest solution for my case. Completing the transaction would not require Thorchain to add new features (e.g. adding a timeout for liquidity deposits or adding new UI elements for manuel withdraw).

Maybe somebody from the team could confirm the correctness of these values for a manual Thor transaction:
Pending pool creation: https://thornode.thorchain.info/thorchain/pool/BNB.USDT-6D8/liquidity_providers
Prerequisite: Fund cap not reached.

`Sender: thor1hsmr2v809n8kmdk2m2l5lu735q3hv7vw52l0tk
Amount: 1000 RUNE
Memo:   ##"+:BNB.USDT-6D8:bnb18xn670lz9fqaympue27a6lfnrjeptgrcrlxy3s"
Recipient:   ##"thor1g98cy3n9mmjrpn0sxmn63lztelera37n8n67c0"`

Adding a timeout for deposits (triggering refund) could be a new feature.

**Comment by stuartwk** [comment]
@gerigag if you send a manual tx, one thing to keep in mind is the "recipient" changes, values are pulled from https://midgard.thorchain.info/v2/thorchain/inbound_addresses.

Pushed a small UI change, you should now be able to withdraw your funds at https://app.asgard.exchange/deposit-sym-recovery/BNB.USDT-6D8. What this does is sends a RUNE withdraw tx for that pool, which will recover asset funds into your wallet.
Due to some wallet updates in xchain, RUNE txs require a minimum of 3 RUNE in the wallet to process the transaction. The gas fees are much lower than that, but it's a kind of safety net for the transaction.

**Comment by gerigag** [comment]
> @gerigag if you send a manual tx, one thing to keep in mind is the "recipient" changes, values are pulled from https://midgard.thorchain.info/v2/thorchain/inbound_addresses.
> 
> Pushed a small UI change, you should now be able to withdraw your funds at https://app.asgard.exchange/deposit-sym-recovery/BNB.USDT-6D8. What this does is sends a RUNE withdraw tx for that pool, which will recover asset funds into your wallet.
> Due to some wallet updates in xchain, RUNE txs require a minimum of 3 RUNE in the wallet to process the transaction. The gas fees are much lower than that, but it's a kind of safety net for the transaction.

Thank you @stuartwk.
I have now been able to withdraw the pending funds via https://app.asgard.exchange/deposit-sym-recovery/BNB.USDT-6D8.
This issue can be closed.
