### ISSUE TITLE
Improve ERC20 token approve UX

### ISSUE THREAD

**Issue by scottyeager** [asgardex/asgard-exchange#413]
I recently used the ERC20 approve button for the first time. In my experience, the interface does not always reflect that a transaction has been submitted after pressing the button (popup to that effect simply doesn't appear). This resulted in multiple submissions and subsequent gas fees.

For users unfamiliar with Ethereum, it's not obvious that this action will require gas. Presenting an estimate of the gas required would be helpful.

Allowing swaps after the approve transaction is processed doesn't seem totally reliable. The interface will sometimes switch very briefly to activating the swap button then revert back. Disconnecting and reconnecting the wallet may help.

If the user doesn't have enough ETH for gas, the approve button is shown even for tokens already approved.

**Comment by stuartwk** [comment]
@scottyeager 👋 thanks for bringing this up. A fix is in the works for this, included in #414

**Comment by scottyeager** [comment]
Glad to hear it, @stuartwk. Thanks :pray:
