### ISSUE TITLE
BNB pool issue - PENDING ASSETS FOUND -

### ISSUE THREAD

**Issue by unobsoletable** [asgardex/asgard-exchange#418]
I tried to enter a BNB pool symmetrically. The BNB was sent but for some reason the RUNE were not and it showed me an error msg of insufficient funds, even though I was sending 50/50 automatically. 

This is the transaction on Thorchain.

<img width="934" alt="Captura de Tela 2021-06-24 às 11 47 26" src="https://user-images.githubusercontent.com/85408530/123283603-f0589780-d4e1-11eb-9ac2-8c98cde5cd1b.png">

I also tried to deposit the pending Rune manually, using the custom deposit tool and the MEMO address, but it showed me the same message of insufficient funds again, even though I had split equally the amount of Rune i had and swapped 50% for BNB prior to trying to enter the pool.

**Comment by stuartwk** [comment]
Hey @unobsoletable, it's recommended that you have at least 3 RUNE in your wallet after the transaction to ensure transactions go through. Are you using the web app or the desktop app?
If you're still having issues, you can remove the pending amount using https://app.asgard.exchange/deposit-sym-recovery. Keep in mind, this will remove everything from that pool, including previously successful deposits.

**Comment by stuartwk** [comment]
Closing this out due to no response. Feel free to open a fresh issue if you encounter anything.
