### ISSUE TITLE
THORSwap - Tried to add BUSD/RUNE liquidity pool but transaction failed - BUSD seems to be added (transaction pending) but RUNE is still in my THOR wallet

### ISSUE THREAD

**Issue by nigelua** [asgardex/asgard-exchange#420]
Hi guys,

I have tried adding equal amounts of BUSD/RUNE into the liquidity pool but the transaction has failed - the BUSD transaction still reads "pending" while RUNE is still stuck in my THOR wallet. I tried to transfer an equal amount of RUNE into the pool but transaction has failed. I also tried to withdraw my BUSD funds but this has failed too: "Submit transaction failed". May I know if there's a way to recover my funds? It seems like they are stuck and there's nothing I can do about it. I had enough BNB in my wallet to cover the gas fees.

I have tried using this to recover my BUSD https://app.asgard.exchange/deposit-sym-recovery , however, I used Binance Chain Wallet and there doesnt seem to be an option to connect it.

Really appreciate your help on this. Thanks! Here are the attached screenshots:

![image](https://user-images.githubusercontent.com/86670052/123812447-ada21f80-d926-11eb-83de-9384046a4b7e.png)

![image](https://user-images.githubusercontent.com/86670052/123817953-2acf9380-d92b-11eb-84ab-3ec0cd5ce0fe.png)

**Comment by thorswapdev** [comment]
@nigelua , please reach out on Discord and open the support ticket. 

Team will get it resolved asap
