### ISSUE TITLE
Microsoft surface pro “no app”

### ISSUE THREAD

**Issue by Howedog** [asgardex/asgard-exchange#424]
I can download Asgardex onto my Microsoft surface pro but but the following comes up.

![4CC46B3F-65A6-4830-9DF1-CA3F22680328](https://user-images.githubusercontent.com/86947528/124428581-3cdc8680-ddb0-11eb-8179-311d742c1129.jpeg)

![798FD7E6-2680-4B88-92D2-E632E57CD4E1](https://user-images.githubusercontent.com/86947528/124428602-436afe00-ddb0-11eb-979b-3d7ad106d3ba.jpeg)

![8223AFD3-BC56-4B74-9331-53D03DCC1B5F](https://user-images.githubusercontent.com/86947528/124428608-449c2b00-ddb0-11eb-8aa2-88e14f167b2f.jpeg)

![C9D88B52-58CB-456C-950E-B98B73F887C9](https://user-images.githubusercontent.com/86947528/124428610-45cd5800-ddb0-11eb-9a47-5ef2a949e463.jpeg)

![DB179D0A-B500-4C4C-9CD6-AC610A36D90D](https://user-images.githubusercontent.com/86947528/124428619-482fb200-ddb0-11eb-8962-436c45367663.jpeg)

can you please find a solution so I can use Asgardex.

Thanks

**Comment by stuartwk** [comment]
Hey @Howedog, this is the repo for the web app.
Feel free to file an issue for the desktop app at https://github.com/thorchain/asgardex-electron.
