### ISSUE TITLE
Add support for LBC 

### ISSUE THREAD

**Issue by paju1986** [asgardex/asgard-exchange#425]
Hello.

I would be great if you could list LBC, the token used by the LBRY Network and Odysee  https://github.com/lbryio, for exchange. 

Thanks you!!

**Comment by stuartwk** [comment]
Hey @paju1986 :wave:, this is more of a THORChain request than an interface request. You can find out about adding protocol support by exploring their Gitlab https://gitlab.com/thorchain. Or feel free to explore the THORChain Dev Community on Discord.
