### ISSUE TITLE
Transaction without success, but no refund

### ISSUE THREAD

**Issue by boalexandre15** [asgardex/asgard-exchange#433]
Hi. I did a swap from BNB to RUNE on Asgardex app, but my transaction had no sucess. My value disappeared. Can you help me, please? 

Transaction https://explorer.binance.org/tx/952976E7AF4F9017CEBC2FC0C37F2F815A85CE5B67D1E485405D89197EA4F760

**Comment by davidp94** [comment]
The network is on hold

Le jeu. 29 juil. 2021 à 18:48, boalexandre15 ***@***.***> a
écrit :

**Comment by boalexandre15** [comment]
But so I lost my funds?

**Comment by davidp94** [comment]
I think you need the network to restart and you'll get your money I think;

Maybe go on Discord

Le jeu. 29 juil. 2021 à 19:06, boalexandre15 ***@***.***> a
écrit :

**Comment by boalexandre15** [comment]
Nice. I’ll try Discord too. Thank you.
