### ISSUE TITLE
Haven't received upgraded THOR.RUNE

### ISSUE THREAD

**Issue by WaltGreywalker** [asgardex/asgard-exchange#436]
I've bought some BEP2 RUNE via Binance and transferred it with some BNB to my Asgard Axchange Wallet. Both turned up under my Asgard BNB Adress. I clicked on upgrade to THOR.RUNE and paid the BNB fee. After a few seconds it showed me that everything it's done => SUCCESS. So I closed the message but the converted RUNE never showed up under my THOR adress. 

TRANSACTION
https://explorer.binance.org/tx/DBDC036F4AB177FCB5C578C09A8C1A1BAA50645E15AC8BB983EDFBE97C89C244

Please help me.

**Comment by stuartwk** [comment]
The THORChain network is currently down, so no transactions are going through. Once the network is back online, it should pick up these transactions. You can follow along on the status of the network on their Twitter or Discord.

**Comment by WaltGreywalker** [comment]
Allright, thank you for explaining. 
I'm quite a newbie and I wasn't aware of that downtime. Next time I'll be better prepared ;)
Thank you again and have a nice day.
