### ISSUE TITLE
Swap RUNE <> AWC

### ISSUE THREAD

**Issue by blazed-bison** [asgardex/asgard-exchange#75]
I seemingly successfully swapped RUNE for AWC, tx # below:

https://testnet-explorer.binance.org/tx/E517531D3168D6A2CDA468573F27C854D0139C24131FB470A02CDD305081B96B

However when trying to swap AWC back to any other asset, it says Insufficient Balance.

Further to that, I am able to select the Insufficient Balance button, and confirm transaction, which then leads to a fail dialog box (triangle with exclamation point icon)
![image](https://user-images.githubusercontent.com/75455869/101104238-cd869480-361e-11eb-91c0-d2f82f65010c.png)

**Comment by stuartkuentzel** [comment]
This should be cleared up a handful of updates, if you encounter it again feel free to open a new issue.
