### ISSUE TITLE
Address selection not intuitive/interactive

### ISSUE THREAD

**Issue by volelliot** [asgardex/asgard-exchange#86]
When you click on the address in the upper-right corner on asgard.exchange, all chains (RUNE, BTC, and BNB) are shown

Intuitively, to select e.g. the RUNE address you would click on the address (the white square in screenshot) instead of the larger shape in which the address is situated. But, the address itself is not interactive. You need to click on any other place inside the larger shape to get to the next "page" (2nd screenshot)

Would be better to make the address interactive as well, since that is the first thing you try to select

![1](https://user-images.githubusercontent.com/78734952/107218530-045a9b80-6a10-11eb-80ad-2905cccc78fb.png)
![2](https://user-images.githubusercontent.com/78734952/107218531-04f33200-6a10-11eb-92dd-120726a0e080.png)

bnb179wwxjm87vrtgms2uq7jyc3v9qjxygufjq2pz3

**Comment by stuartkuentzel** [comment]
Hey @volelliot, what browser are you using for this? I'm having trouble reproducing the issue. I just tested it in Brave, Chrome, and Safari, and the address itself is clickable.

**Comment by volelliot** [comment]
Hey @stuartkuentzel this is on Mozilla

**Comment by volelliot** [comment]
This is also the case when you want to click on the transaction-id to go to the block explorer. So probably doesn't work on any of the spots where the address and transaction-id should be clickable.

![3a](https://user-images.githubusercontent.com/78734952/107403733-c475e000-6b05-11eb-8f80-d1e135d851e7.png)
