### ISSUE TITLE
Balances not updating

### ISSUE THREAD

**Issue by satb** [asgardex/asgard-exchange#87]
Got test btc from the btc testnet faucet.
Swapped for some bnb.
0.01 btc should fetch 0.6 bnb.
btc transaction confirmed
bnb balance not updating on asgard.exchange even though navigating to the bnb testnet explorer shows the right balance

Here is the btc txn confirmation - https://blockstream.info/testnet/tx/e5b2b3286d2c50dcfb5b073d0e3e94c76cdd17684ca7d81b852278bae45380a3

Here is the bnb txn with balance
https://testnet-explorer.binance.org/address/tbnb15fra03ey4as8cag7czxh6as5gxq0g8ac85dwzl

And here is the asgard UI showing no bnb balance yet

![image](https://user-images.githubusercontent.com/2095367/107237785-f7bc5000-69db-11eb-9474-b02e29993881.png)

**Comment by stuartkuentzel** [comment]
Balances have been reworked a good amount and seems to be working. If still occurring, feel free to reopen or create a new issue...
