### ISSUE TITLE
Incorrect amount of RUNE balance in Asgardex

### ISSUE THREAD

**Issue by agomezrodriguez** [asgardex/asgard-exchange#89]
After performed a swap between BNB and RUNE via runefaucetbot it is showing different balances on Asgardex and Binance Chain Explorer:

https://testnet-explorer.binance.org/address/tbnb1m36xcw2y3ev6kpakdy8xcfpu4rh0ztxhx6ezjy
<img width="1238" alt="Captura de pantalla 2021-02-08 a las 17 59 15" src="https://user-images.githubusercontent.com/2371150/107255590-c4f47500-6a38-11eb-9cc4-fd7900ee7ea3.png">
<img width="426" alt="Captura de pantalla 2021-02-08 a las 17 59 08" src="https://user-images.githubusercontent.com/2371150/107255598-c625a200-6a38-11eb-9390-8c0fb06cb511.png">

**Comment by stuartkuentzel** [comment]
Hey @agomezrodriguez, the above balance is your native RUNE amount, not BNB RUNE amount. If you did a BNB -> RUNE swap, that would be to native RUNE. Basically, the only thing you can do with BNB RUNE now is upgrade it to native RUNE in the user settings.
There has been some confusion about it, so we'll try to make the UI a bit clearer. Closing for now, let me know if you have other questions on it.

**Comment by agomezrodriguez** [comment]
Thanks @stuartkuentzel in order to increase the user adoption and engagement, I think those differentiations from RUNE chains must be transparent. I understand that at the end there will be just one kind of RUNE token, not 2 as we have nowadays.

**Comment by agomezrodriguez** [comment]
Just seen you have just added a modal window to help users realize they have RUNE in different chains which is great. 
<img width="563" alt="Captura de pantalla 2021-02-12 a las 12 40 56" src="https://user-images.githubusercontent.com/2371150/107764350-5b25e500-6d30-11eb-9ccf-78c9f2a57287.png"> but once I have converted my 1000 Binance chain tokes to native RUNE chain, they are not shown in Asgardex.
