### ISSUE TITLE
 the amount of the BUSD / RUNE pair is not good

### ISSUE THREAD

**Issue by Jaxxou** [asgardex/asgard-exchange#95]
the amount of the BUSD / RUNE par is not good

here some screenshot, with the real actual price Rune = 4.41 $
 with 1 Busd we must have less than 1 Rune ! around 0.22 !

Here some pics 
![Capture 2](https://user-images.githubusercontent.com/78721473/107311909-b47be300-6aa8-11eb-9f48-319f1999bc08.JPG)
![prix pas bon](https://user-images.githubusercontent.com/78721473/107311930-c52c5900-6aa8-11eb-8a84-5f10f8f2786f.JPG)

Moreover, Dev you work hard ! thank you very much 

bnbadress
bnb16g22ty7974vsez06phd5hy6ulwx7zkctzy8sds

**Comment by stuartkuentzel** [comment]
This has to do with the testnet pools being imbalanced, so this is expected. I tested out a BUSD -> RUNE transaction just to make sure it wasn't interface. I received around the estimated output. Closing as this has to do with the testnet THORChain network itself, not the asgardex interface.
